---
title: "HPC Desktop"
cluster: {{ cluster_name }} 
submit: "submit/submit.yml.erb"
attributes:
  desktop: "xfce"

form:
  - desktop
  - bc_num_hours
  - bc_partition
  - bc_num_slots
  - bc_num_mems
