---
- name: Clone template repo from upstream
  git:
    repo: 'https://github.com/OSC/bc_osc_rstudio_server.git'
    dest: '/var/www/ood/apps/sys/bc_rstudio_server'
    force: yes

- name: Replace form.yml
  template:
    src: form.yml
    dest: /var/www/ood/apps/sys/bc_rstudio_server/form.yml

- name: Replace form submission template
  copy:
    src: submit.yml
    dest: /var/www/ood/apps/sys/bc_rstudio_server/submit.yml.erb

- name: Modify script.sh.erb
  replace:
    path: /var/www/ood/apps/sys/bc_rstudio_server/template/script.sh.erb
    regexp: '(module purge.*)'
    replace: '#\1'

