---
cluster: "{{ cluster_name }}"
attributes:
  version:
    widget: select
    label: "R version"
    help: "This defines the version of R you want to load."
    options:
      # Define functioning R version overloads using a colon after the module load statement
{% for ver in r_versions %}
      - [ "{{ ver.full }}", "rstudio_singularity/{{ ver.full }}"]
{% endfor %}

form:
  - version
  - bc_num_hours
  - bc_partition
  - bc_num_slots
  - bc_num_mems
  - bc_email_on_started
