---
- shell: ls /var/www/ood/apps/sys/dashboard/public/assets/application*.css
  ignore_errors: yes
  register: css_file_name

- name: Copy CSS file from Dashboard App
  copy:
    src: "{{ css_file_name.stdout }}"
    dest: /var/www/ood/public/application.css
    remote_src: yes

- name: Put static HTML file in place
  copy:
    src: index.html
    dest: /var/www/ood/register

- name: Update ood portal to serve static HTML
  replace:
    path: /etc/ood/config/ood_portal.yml
    regexp: "^#?(register_root:).*$"
    replace: "\\1 '/var/www/ood/register'"

- name: Build the updated Apache config
  command: /opt/ood/ood-portal-generator/sbin/update_ood_portal
  ignore_errors: yes

