---
- name: install the latest version of libXtst
  yum:
    name: libXt
    state: latest

- name: Create directory
  file:
    path: "{{ matlab_install_root }}/{{ item.ver }}"
    state: directory
    mode: 0755
  with_items: "{{ matlab_versions }}"

- name: Extract matlab
  unarchive:
    src: "{{ item.url }}"
    dest: "{{ matlab_install_root }}/{{ item.ver }}"
    remote_src: yes
  with_items: "{{ matlab_versions }}"

- name: Create directory
  file:
    path: "{{ matlab_modulefiles_dir }}"
    state: directory
    mode: 0755

- name: Copy modulefile from template to module path
  template:
    src: matlab.j2
    dest: "{{ matlab_modulefiles_dir }}/{{ item.ver }}"
  with_items: "{{ matlab_versions }}"
