---
- name: Enable Copr Repos
  shell: yum -y copr enable "{{ item.repo_name }}"
  with_items: "{{ copr_repos }}"
  when: enable_copr == true and inventory_hostname in item.host

- name: Install mod_wsgi for httpd24
  yum: name="{{ mod_wsgi_pkg_name }}" state=latest

- name: Install pip via yum
  yum: name=python2-pip state=latest

- name: Install virtualenv via pip
  pip: name=virtualenv state=latest

- name: Remove existing user register app install
  file:
    path: "{{ user_register_app_path }}"
    state: absent

- name: Creates directory to clone the user register app
  file:
    path: "{{ user_register_app_path }}"
    state: directory

- name: Clone user register app form from gitlab
  git:
    repo: "{{ user_register_app_repo }}"
    dest: "{{ user_register_app_path }}"

- name: Install requirements in virtualenv
  pip:
    requirements: requirements.txt
    virtualenv: venv
    chdir: "{{ user_register_app_path }}"

