---
- name: Install Singularity
  shell: |
    source /etc/profile.d/lmod.sh
    export EASYBUILD_PREFIX={{ easybuild_prefix }}
    module load EasyBuild
    eb Singularity-{{ singularity_ver }}-GCC-5.4.0-2.26.eb --try-toolchain-name=dummy -r --force
  become_user: build
  args:
    executable: /bin/bash
    chdir: /tmp

- name: Singularity post install steps(1/3) - chown
  file:
    path: "{{ easybuild_prefix }}/software/Singularity/{{ item }}"
    owner: root
    group: root
  with_items:
    - "{{ singularity_ver }}/etc/singularity/singularity.conf"
    - "{{ singularity_ver }}/libexec/singularity/bin/action-suid"
    - "{{ singularity_ver }}/libexec/singularity/bin/mount-suid"
    - "{{ singularity_ver }}/libexec/singularity/bin/start-suid"
    - "{{ singularity_ver }}/var/singularity/mnt/container"

- name: Singularity post install steps(2/3) - chmod
  file:
    path: "{{ easybuild_prefix }}/software/Singularity/{{ item }}"
    mode: '4755'
  with_items:
    - "{{ singularity_ver }}/libexec/singularity/bin/action-suid"
    - "{{ singularity_ver }}/libexec/singularity/bin/mount-suid"
    - "{{ singularity_ver }}/libexec/singularity/bin/start-suid"

- name: Singularity post install steps(3/3) - chmod
  file:
    path: "{{ easybuild_prefix }}/software/Singularity/{{ item }}"
    mode: '+s'
  with_items:
    - "{{ singularity_ver }}/libexec/singularity/bin/action-suid"
    - "{{ singularity_ver }}/libexec/singularity/bin/mount-suid"
    - "{{ singularity_ver }}/libexec/singularity/bin/start-suid"

- name: Clone template modulefiles from upstream
  git:
    repo: 'https://github.com/nickjer/singularity-rstudio.git'
    dest: '/tmp/singularity-rstudio'
    force: yes

- name: Create folder for different R versions
  file:
    path: "{{ r_install_root }}/{{ item.full }}"
    state: directory
  with_items:
    "{{ r_versions }}"

- name: Create library folder for different R versions
  file:
    path: "{{ r_install_root}}/library-{{ item.short }}"
    state: directory
  with_items:
    "{{ r_versions }}"

- name: Download Rstudio singularity image
  shell: |
    source /etc/profile.d/lmod.sh
    module load Singularity
    SINGULARITY_PULLFOLDER={{ item.full }} singularity pull --name singularity-rstudio.simg shub://nickjer/singularity-rstudio:{{ item.full }}
  with_items:
    "{{ r_versions }}"
  args:
    chdir: "{{ r_install_root }}"

- name: Generate modulefiles for each version
  file:
    path: "{{ r_modulefiles_dir }}"
    state: directory

- template:
    src: modulefiles/rstudio.j2
    dest: "{{ r_modulefiles_dir }}/{{ item.full }}.lua"
  vars:
    ver: "{{ item }}"
  with_items:
    "{{ r_versions }}"

- name: Move modulefiles into shared folder
  command: mv {{ src }} {{ dest }}
  args:
    creates: "{{ dest }}"
    removes: "{{ src }}"
  vars:
    src: /tmp/singularity-rstudio/example_module/bin
    dest: "{{ r_install_root }}/bin"

- name: Clean up
  file:
    path: /tmp/singularity-rstudio
    state: absent
