---
- name: Copy the configure file for Dashboard app
  template:
    src: dashboard/env_local.js
    dest: /var/www/ood/apps/sys/dashboard/.env.local

- name: Add shared directories into files menu
  template:
    src: dashboard/ood_rb.j2
    dest: /var/www/ood/apps/sys/dashboard/config/initializers/ood.rb
