---
- name: Copy the configure file for Dashboard app
  template:
    src: dashboard/env_local.j2
    dest: /var/www/ood/apps/sys/dashboard/.env.local

- name: Add shared directories into files menu
  template:
    src: dashboard/ood_rb.j2
    dest: /var/www/ood/apps/sys/dashboard/config/initializers/ood.rb

- name: Add cheaha logo image
  copy:
    src: cheaha-logo.png
    dest: /var/www/ood/apps/sys/dashboard/app/assets/images/cheaha-logo.png

- name: Check if cheaha logo has been set
  shell: grep cheaha-logo.png /var/www/ood/apps/sys/dashboard/app/helpers/dashboard_helper.rb
  ignore_errors: yes
  register: cheaha_logo

- name: Add cheaha logo to Dashboard
  replace:
    path: /var/www/ood/apps/sys/dashboard/app/helpers/dashboard_helper.rb
    regexp: '(image_tag\("[^"]*)OpenOnDemand_stack_RGB.svg(.*)$'
    replace: '\1cheaha-logo.png\2'
    backup: yes
  when: cheaha_logo.stdout == ""

- name: Rebuild assets for Dashboard app
  shell: |
    scl enable git19 rh-ruby22 nodejs010 -- bin/rake assets:clobber RAILS_ENV=production
    scl enable git19 rh-ruby22 nodejs010 -- bin/rake assets:precompile RAILS_ENV=production
  args:
    chdir: /var/www/ood/apps/sys/dashboard

- name: Force Dashboard app to restart
  file:
    path: /var/www/ood/apps/sys/dashboard/tmp/restart.txt
    state: touch

- name: Copy the configure file for Active Jobs app
  template:
    src: env_local.j2
    dest: "/var/www/ood/apps/sys/{{ app_name }}/.env.local"
  vars:
    app_name: "activejobs"

- name: Rebuild assets for Active Jobs app
  shell: |
    scl enable git19 rh-ruby22 nodejs010 -- bin/rake assets:clobber RAILS_ENV=production
    scl enable git19 rh-ruby22 nodejs010 -- bin/rake assets:precompile RAILS_ENV=production
  args:
    chdir: /var/www/ood/apps/sys/activejobs

- name: Force Active Jobs app to restart
  file:
    path: /var/www/ood/apps/sys/activejobs/tmp/restart.txt
    state: touch

- name: Copy the configure file for Job Composer app
  template:
    src: env_local.j2
    dest: "/var/www/ood/apps/sys/{{ app_name }}/.env.local"
  vars:
    app_name: "myjobs"

- name: Rebuild assets for Job Composer app
  shell: |
    scl enable git19 rh-ruby22 nodejs010 -- bin/rake assets:clobber RAILS_ENV=production
    scl enable git19 rh-ruby22 nodejs010 -- bin/rake assets:precompile RAILS_ENV=production
  args:
    chdir: /var/www/ood/apps/sys/myjobs

- name: Force Job Composer app to restart
  file:
    path: /var/www/ood/apps/sys/myjobs/tmp/restart.txt
    state: touch
