name: Ansible lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get file changes
        id: changed-files
        uses: tj-actions/changed-files@v28.0.0

      - name: Lint Ansible Playbook
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible-community/ansible-lint-action@main
        # optional:
        with:
          path: ${{ steps.changed-files.outputs.all_changed_files }}
