name: Build OpenStack image

on:
  pull_request:
    branch:
      - test-action

jobs:
  publish_image:
    name: Build OpenStack image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Clone packer repo
        run: |
          git clone https://gitlab.rc.uab.edu/rc/packer-openstack-hpc-image.git

      - name: Check cwd
        run: ls
      - name: Check cwd
        run: ls ..
